### ISSUE TITLE
add websockets to awesome internet computer repo

### ISSUE THREAD

**Issue by letmejustputthishere** [omnia-network/ic-websocket-gateway#23]
https://github.com/dfinity/awesome-internet-computer

**Comment by Luca8991** [comment]
@letmejustputthishere what section would you suggest? Should we also add our SDKs to the CDKs and Client libraries sections?

**Comment by letmejustputthishere** [comment]
not sure, if it doesnt fit anywhere you can create your own category. yes please add everything relevant :)
