### ISSUE TITLE
may I need setup some varls？when I run by docker image from docker hub 

### ISSUE THREAD

**Issue by johnxiaohe** [omnia-network/ic-websocket-gateway#34]
thread 'main' panicked at src/ic-websocket-gateway/src/manager.rs:27:14:
could not get new agent: TransportError(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(4943), path: "/api/v2/status", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) })

**Comment by ilbertt** [comment]
I think you have to set the `--ic-network-url` properly:

```bash
docker run --rm -p 8080:8080 omniadevs/ic-websocket-gateway --ic-network-url http://host.docker.internal:4943
```

This way, Docker resolves the IP to your host machine, where the dfx local replica is supposed to be running

**Comment by ilbertt** [comment]
@johnxiaohe this issue has been closed automatically after merging an update to the docker guide in the README.

Feel free to reopen it if you still have any issues.

**Comment by johnxiaohe** [comment]
> I think you have to set the `--ic-network-url` properly:
> 
> ```shell
> docker run -p 8080:8080 omniadevs/ic-websocket-gateway --ic-network-url http://host.docker.internal:4943
> ```
> 
> This way, Docker resolves the IP to your host machine, where the dfx local replica is supposed to be running.
> 
> @johnxiaohe let me know if it works!

Work very health!!! Thanks!!!
